### ISSUE TITLE
Revisão do documento de arquitetura

### ISSUE THREAD

**Issue by JonathasSL** [JonathasSL/SmartParking-web#34]
- [x] #48 Diagrama de componentes @raviassis 
- [x] #49 Diagrama Implantação @raviassis 
- [x] #50 Diagrama de Classe @H1bertto
- [x] #51 Documentar os endpoints da API @H1bertto 
- [x] #52 Requisitos @H1bertto 
- [x] #53 Apresentação @lucasmhv 
- [x] #54 Casos de Uso @JonathasSL
